const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs/promises');
(async()=>{
 const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const old={schemaVersion:7,logs:[{id:'fixture',date:'2026-10-07',weight:82,sun:0,custom:'preserved'}],profile:{age:60,height:180,weight:82},cyclePerformance:{legacy:{load:37.5}},mealsEaten:{'2026-10-07':{breakfast:true}},futureField:{kept:42}};
 await context.addInitScript(data=>{if(!localStorage.getItem('phases60_v5.7')){localStorage.setItem('phases60_v5.7',JSON.stringify(data));localStorage.setItem('phases60_v5.7_cycle_charges',JSON.stringify([{week:1,dc:37.5},{week:99,custom:10}]));localStorage.setItem('phase60_theme','light');}},{...old});
 await page.goto('http://127.0.0.1:8765/index.html');await page.waitForFunction(()=>typeof renderV59==='function');
 assert.deepEqual(await page.evaluate(()=>state.logs[0]),old.logs[0]);assert.deepEqual(await page.evaluate(()=>state.futureField),old.futureField);assert.equal(await page.title(),'Phase60Plus V5.9 PWA — Construction musculaire');
 await page.click('[data-page="recuperation"]');await page.fill('#v59Hours','6.5');await page.fill('#v59Awakenings','3');await page.fill('#v59Urinations','2');await page.check('#v59Tired');await page.click('#v59SleepForm button');assert.match(await page.textContent('#v59RecoveryAdvice'),/30–40/);assert.ok(await page.evaluate(()=>recoveryScore()<=69));
 await page.click('[data-page="pectoraux"]');assert.match(await page.textContent('#v59ChestPlan'),/2 × 8–12/);for(let i=0;i<3;i++){await page.fill('#v59Load'+i,'16');await page.fill('#v59Reps'+i,'10');await page.fill('#v59Rir'+i,'3');}await page.click('#v59SaveChest');assert.match(await page.textContent('#v59ChestFeedback'),/enregistrée/);
 await page.click('[data-page="ventre"]');await page.check('#v59Core1');await page.click('#v59SaveCore');
 await page.click('[data-page="nutrition"]');for(const[id,val]of Object.entries({v59Protein:'150',v59CarbLunch:'60',v59CarbSnack:'30',v59CarbDinner:'60'}))await page.fill('#'+id,val);await page.check('#v59Eggs');await page.click('#v59NutritionForm button');assert.match(await page.textContent('#v59NutritionFeedback'),/dans le repère/);
 await page.reload();await page.click('[data-page="recuperation"]');assert.equal(await page.inputValue('#v59Hours'),'6.5');await page.click('[data-page="ventre"]');assert.equal(await page.isChecked('#v59Core1'),true);
 await page.click('[data-page="profil"]');const downloadPromise=page.waitForEvent('download');await page.evaluate(()=>exportBackup());const download=await downloadPromise;const backup=JSON.parse(await fs.readFile(await download.path(),'utf8'));assert.equal(backup.version,'5.9');assert.deepEqual(backup.state.logs[0],old.logs[0]);assert.ok(backup.state.v59.chest);assert.equal(backup.appStorage.phase60_theme,'light');const priorCharges=backup.charges;
 // Exercise actual restore handler, including FileReader and reload.
 await page.evaluate(()=>{state.logs=[];state.v59={};saveState();});await page.setInputFiles('#restoreBackupFile',{name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.waitForEvent('load');assert.deepEqual(await page.evaluate(()=>state.logs[0]),old.logs[0]);assert.ok(await page.evaluate(()=>state.v59.chest));assert.equal(await page.evaluate(()=>localStorage.getItem(CYCLE_STORAGE_KEY)),priorCharges);
 await page.click('[data-page="suivi"]');const logDownload=page.waitForEvent('download');await page.click('#exportBtn');const logs=JSON.parse(await fs.readFile(await (await logDownload).path(),'utf8'));assert.equal(logs[0].custom,'preserved');await page.setInputFiles('#importBtn',{name:'partial.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify([{date:'2026-10-07',sun:0,note:'roundtrip'}]))});await page.waitForFunction(()=>state.logs[0].note==='roundtrip');assert.equal(await page.evaluate(()=>state.logs[0].weight),82);
 await page.setInputFiles('#importBtn',{name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"wrong":true}')});await page.waitForFunction(()=>document.getElementById('saveMsg').textContent.includes('invalide'));assert.equal(await page.evaluate(()=>state.logs.length),1);
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.reload();await page.waitForFunction(()=>navigator.serviceWorker.controller!==null);const manifest=await page.evaluate(async()=>await (await fetch('./manifest.webmanifest')).json());assert.equal(manifest.display,'standalone');for(const icon of manifest.icons){const dimensions=await page.evaluate(async src=>{const i=new Image();i.src=src;await i.decode();return [i.naturalWidth,i.naturalHeight];},icon.src);assert.equal(dimensions.join('x'),icon.sizes);}
 await page.evaluate(async()=>{await caches.open('unrelated-cache');});await context.setOffline(true);await page.reload();await page.waitForFunction(()=>typeof renderV59==='function');await page.click('[data-page="pectoraux"]');assert.match(await page.textContent('#v59ChestFeedback'),/enregistrée/);assert.ok(await page.evaluate(()=>state.v59.nutrition));await page.screenshot({path:'/tmp/phaseplus60-v59-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log('PASS: legacy storage, four modules, reload, complete backup restore, partial JSON import, invalid JSON rejection, mobile UI, manifest/icons, service worker and offline reload');await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
