const {test}=require('node:test');const assert=require('node:assert/strict');const api=require('../data-v59.js');
class Storage{constructor(values={}){this.values={...values};}get length(){return Object.keys(this.values).length;}key(i){return Object.keys(this.values)[i];}getItem(k){return this.values[k]??null;}setItem(k,v){this.values[k]=String(v);}removeItem(k){delete this.values[k];}}
const key='phases60_v5.7',cycle=key+'_cycle_charges';
test('partial import preserves IDs, unknown fields, omitted measurements and zero',()=>{const old=[{id:'old',date:'2026-10-08',weight:82,sun:3,custom:'kept'}];const r=api.mergeLogs(old,[{date:'2026-10-08',sun:0,note:'new'}],()=> 'new');assert.equal(r.logs[0].weight,82);assert.equal(r.logs[0].sun,0);assert.equal(r.logs[0].custom,'kept');assert.equal(r.logs[0].id,'old');assert.equal(old[0].note,undefined);});
test('invalid batch does not change existing data',()=>{const old=[{date:'2026-10-08',weight:82}];assert.throws(()=>api.mergeLogs(old,[{date:'2026-10-08',poids:80},{date:'2026-02-30'}],()=> 'id'));assert.equal(old[0].weight,82);assert.throws(()=>api.mergeLogs(old,[{date:'2026-10-08',poids:'oops'}],()=> 'id'));});
test('French legacy fields and decimal commas remain importable',()=>{const r=api.mergeLogs([],[{date:'2026-10-08',poids:'82,3',taille:90,mg:0}],()=> 'id');assert.equal(r.logs[0].weight,82.3);assert.equal(r.logs[0].fat,0);});
test('complete backup restores modules, historical charges, theme, unknown fields',()=>{const state={logs:[],profile:{weight:82},v59:{nights:{day:{hours:6.5}}},future:{kept:true}};const src=new Storage({[key]:JSON.stringify(state),[cycle]:'[{"week":1,"dc":37.5},{"week":99}]',phase60_theme:'light',unrelated:'keep'});const backup=api.validateBackup(JSON.parse(JSON.stringify(api.makeBackup(state,src,cycle))),cycle);const dest=new Storage({unrelated:'untouched'});api.restore(dest,key,cycle,backup.state,backup);assert.deepEqual(JSON.parse(dest.getItem(key)),state);assert.equal(dest.getItem(cycle),src.getItem(cycle));assert.equal(dest.getItem('phase60_theme'),'light');assert.equal(dest.getItem('unrelated'),'untouched');});
test('V5.7 backup compatibility and invalid backup rejection',()=>{assert.equal(api.validateBackup({version:'5.7.1',schemaVersion:7,state:{logs:[]},charges:'[]'},cycle).charges,'[]');for(const x of [{},[],{state:{logs:'bad'}},{state:{logs:[]},charges:'{}'},{state:{logs:[]},appStorage:{foreign:'x'}},{schemaVersion:99,state:{logs:[]}}])assert.throws(()=>api.validateBackup(x,cycle));});
test('failed restoration rolls back existing state',()=>{const s=new Storage({[key]:'old',[cycle]:'old charges'});let failed=false;const write=s.setItem.bind(s);s.setItem=(k,v)=>{if(k===cycle&&!failed){failed=true;throw Error('quota');}write(k,v);};assert.throws(()=>api.restore(s,key,cycle,{logs:[]},{appStorage:{},charges:'[]'}));assert.equal(s.getItem(key),'old');assert.equal(s.getItem(cycle),'old charges');assert.ok(s.getItem('phases60_v5.9_before_restore'));});
